# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"                # Root directory for the Go project
    schedule:
      interval: "weekly"          # Run Dependabot weekly
    open-pull-requests-limit: 10  # Limit the number of open PRs

  - package-ecosystem: "npm"
    directory: "sitebuilder"  # Path to the npm project inside the repository
    schedule:
      interval: "weekly"              # Run Dependabot weekly
    open-pull-requests-limit: 10      # Limit the number of open PRs


